# install       pip3 install pre-commit
# run           pre-commit run -a
# update deps   pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      # - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      # - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.331
#    hooks:
#    - id: pyright
#      additional_dependencies:
#      - shepherd-core[elf,inventory,dev,test]
#      - shepherd-data[dev,test]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.8.1'
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        # manual run: ruff check . --preview

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: "v1.6.1"
#    hooks:
#      - id: mypy
# TODO: activate mypy -> some work to fix type-annotations
# run manually in subproject for now: mypy .

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        additional_dependencies: ["tomli"]  # for py<3.11
#        exclude: \.(sch|brd|lbr)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD013"] # ignore line length

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.23
    hooks:
      - id: validate-pyproject

# TODO: github.com/PyCQA/pydocstyle

# default_language_version:
#    python: python3.8
