line-length = 100
target-version = "py38"

[lint]
select = ["ALL"]
ignore = [
    "N802", "N803", "N806", "N815", "N816", # naming (si-units should stay)
    "PLR2004", # magic values
    "TID252", # relative imports from parent
    "PLR0904", # complexity
    "PLR0911", "PLR0912", # complexity
    "PLR0913", "PLR0915", # complexity
    "C901", # complexity
    "ANN101", "ANN102", # self & cls not type-annotated
    "ANN401",  # Any as valid type
    "COM812", # trailing comma, same line
    "PLC0415",  # import in FN
    "TD002", "TD003", "TD005", "FIX002",  # TODOs
    "D203", # blank line before Docstring
    "D105", # docstring in magic methods
]

[lint.per-file-ignores]
"*/tests/**" = ["ARG", "S", "D", "T201"]
"*/examples/**" = ["INP001"]  # no namespace

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[lint.isort]
force-single-line = true

[lint.pyupgrade]
keep-runtime-typing = true

[format] # per default like Black
docstring-code-format = true
