name: Publish Data-Package to PyPi

on:
  release:
    types: [published]
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:

  publish-core:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/shepherd-core
    permissions:
      id-token: write

    steps:

      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build data-package 🧱
        run: python -m build
        working-directory: "./shepherd_data"

      - name: Publish package 🥳
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: shepherd_data/dist/
