name: Release tagged Commit

on:
  workflow_call:

permissions:
  contents: write

jobs:
  run-unittests:
    uses: ./.github/workflows/py_unittest.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - run-unittests
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
