name: Release tagged Commit

on:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  run-unittests:
    uses: ./.github/workflows/python_app.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - run-unittests
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
