name: Release tagged Commit

on:
  workflow_call:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  run-unittests:
    uses: ./.github/workflows/py_unittest.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - run-unittests
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Release 🏃
        uses: softprops/action-gh-release@v2
